// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wrapper.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "wrapper.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Exchange {

namespace {

const ::google::protobuf::Descriptor* Wrapper_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Wrapper_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_wrapper_2eproto() {
  protobuf_AddDesc_wrapper_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "wrapper.proto");
  GOOGLE_CHECK(file != NULL);
  Wrapper_descriptor_ = file->message_type(0);
  static const int Wrapper_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Wrapper, messageid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Wrapper, payload_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Wrapper, payloadsize_),
  };
  Wrapper_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Wrapper_descriptor_,
      Wrapper::default_instance_,
      Wrapper_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Wrapper, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Wrapper, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Wrapper));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_wrapper_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Wrapper_descriptor_, &Wrapper::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_wrapper_2eproto() {
  delete Wrapper::default_instance_;
  delete Wrapper_reflection_;
}

void protobuf_AddDesc_wrapper_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\rwrapper.proto\022\010Exchange\"B\n\007Wrapper\022\021\n\t"
    "MessageId\030\001 \002(\t\022\017\n\007Payload\030\002 \002(\014\022\023\n\013Payl"
    "oadSize\030\003 \002(\r", 93);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "wrapper.proto", &protobuf_RegisterTypes);
  Wrapper::default_instance_ = new Wrapper();
  Wrapper::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_wrapper_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_wrapper_2eproto {
  StaticDescriptorInitializer_wrapper_2eproto() {
    protobuf_AddDesc_wrapper_2eproto();
  }
} static_descriptor_initializer_wrapper_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Wrapper::kMessageIdFieldNumber;
const int Wrapper::kPayloadFieldNumber;
const int Wrapper::kPayloadSizeFieldNumber;
#endif  // !_MSC_VER

// ToDo: Requires protoc plugin to modify call to base constructor
Wrapper::Wrapper()
  : InternalMessage() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Exchange.Wrapper)
}

void Wrapper::InitAsDefaultInstance() {
}

// ToDo: Requires protoc plugin to modify call to base constructor
Wrapper::Wrapper(const Wrapper& from)
  : InternalMessage() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Exchange.Wrapper)
}

void Wrapper::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  messageid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  payload_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  payloadsize_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Wrapper::~Wrapper() {
  // @@protoc_insertion_point(destructor:Exchange.Wrapper)
  SharedDtor();
}

void Wrapper::SharedDtor() {
  if (messageid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete messageid_;
  }
  if (payload_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete payload_;
  }
  if (this != default_instance_) {
  }
}

void Wrapper::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Wrapper::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Wrapper_descriptor_;
}

const Wrapper& Wrapper::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_wrapper_2eproto();
  return *default_instance_;
}

Wrapper* Wrapper::default_instance_ = NULL;

Wrapper* Wrapper::New() const {
  return new Wrapper;
}

void Wrapper::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    if (has_messageid()) {
      if (messageid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        messageid_->clear();
      }
    }
    if (has_payload()) {
      if (payload_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        payload_->clear();
      }
    }
    payloadsize_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Wrapper::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Exchange.Wrapper)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string MessageId = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_messageid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->messageid().data(), this->messageid().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "messageid");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_Payload;
        break;
      }

      // required bytes Payload = 2;
      case 2: {
        if (tag == 18) {
         parse_Payload:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_payload()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_PayloadSize;
        break;
      }

      // required uint32 PayloadSize = 3;
      case 3: {
        if (tag == 24) {
         parse_PayloadSize:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &payloadsize_)));
          set_has_payloadsize();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Exchange.Wrapper)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Exchange.Wrapper)
  return false;
#undef DO_
}

void Wrapper::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Exchange.Wrapper)
  // required string MessageId = 1;
  if (has_messageid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->messageid().data(), this->messageid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "messageid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->messageid(), output);
  }

  // required bytes Payload = 2;
  if (has_payload()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->payload(), output);
  }

  // required uint32 PayloadSize = 3;
  if (has_payloadsize()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->payloadsize(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Exchange.Wrapper)
}

::google::protobuf::uint8* Wrapper::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Exchange.Wrapper)
  // required string MessageId = 1;
  if (has_messageid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->messageid().data(), this->messageid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "messageid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->messageid(), target);
  }

  // required bytes Payload = 2;
  if (has_payload()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->payload(), target);
  }

  // required uint32 PayloadSize = 3;
  if (has_payloadsize()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->payloadsize(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Exchange.Wrapper)
  return target;
}

int Wrapper::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string MessageId = 1;
    if (has_messageid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->messageid());
    }

    // required bytes Payload = 2;
    if (has_payload()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->payload());
    }

    // required uint32 PayloadSize = 3;
    if (has_payloadsize()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->payloadsize());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Wrapper::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Wrapper* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Wrapper*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Wrapper::MergeFrom(const Wrapper& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_messageid()) {
      set_messageid(from.messageid());
    }
    if (from.has_payload()) {
      set_payload(from.payload());
    }
    if (from.has_payloadsize()) {
      set_payloadsize(from.payloadsize());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Wrapper::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Wrapper::CopyFrom(const Wrapper& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Wrapper::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void Wrapper::Swap(Wrapper* other) {
  if (other != this) {
    std::swap(messageid_, other->messageid_);
    std::swap(payload_, other->payload_);
    std::swap(payloadsize_, other->payloadsize_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Wrapper::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Wrapper_descriptor_;
  metadata.reflection = Wrapper_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Exchange

// @@protoc_insertion_point(global_scope)
